-- Add tracking columns to routes table for KPI comparison
ALTER TABLE public.routes ADD COLUMN IF NOT EXISTS is_optimized BOOLEAN DEFAULT false;
ALTER TABLE public.routes ADD COLUMN IF NOT EXISTS theoretical_distance_km FLOAT;
ALTER TABLE public.routes ADD COLUMN IF NOT EXISTS theoretical_duration_min INTEGER;
ALTER TABLE public.routes ADD COLUMN IF NOT EXISTS stops_count INTEGER;
ALTER TABLE public.routes ADD COLUMN IF NOT EXISTS logic_parameters_snapshot JSONB;

-- Enable RLS updates if needed (assuming already enabled)
COMMENT ON COLUMN public.routes.is_optimized IS 'Flags if the route was generated by the Google Route Optimization API';
COMMENT ON COLUMN public.routes.theoretical_distance_km IS 'Planned distance provided by the optimizer/planner';
COMMENT ON COLUMN public.routes.theoretical_duration_min IS 'Planned duration provided by the optimizer/planner';
